"""The questions for main.py quiz."""

questions = {
    "What is the chemical symbol for gold?": ["Au", "Ag", "Fe", "Pb", "Au"],
    "What is the smallest prime number?": ["1", "2", "3", "4", "2"],
    "What is the speed of light?": ["300,000 km/s", "150,000 km/s", "450,000 km/s", "600,000 km/s", "300,000 km/s"],
    "What is the currency of Japan?": ["Yen", "Won", "Dollar", "Euro", "Yen"],
    "What is the tallest mountain in the world?": ["K2", "Kilimanjaro", "Everest", "Denali", "Everest"],
    "What is the largest ocean on Earth?": ["Atlantic", "Indian", "Arctic", "Pacific", "Pacific"],
    "What is the capital of Australia?": ["Sydney", "Canberra", "Melbourne", "Brisbane", "Canberra"],
    "What is the most spoken language in the world?": ["English", "Mandarin", "Spanish", "Hindi", "Mandarin"],
    "What is the most widely used programming language?": ["Python", "Java", "C++", "JavaScript", "Python"],
    "What is the largest organ in the human body?": ["Heart", "Liver", "Skin", "Brain", "Skin"],
    "How many unique colours does the flag of South Africa have?": ["3", "4", "5", "6", "6"],
    "What is the capital of Switzerland?": ["Zurich", "Bern", "Geneva", "Lausanne", "Bern"],
    "When was the first manned moon landing?": ["1969", "1970", "1968", "1971", "1969"],
    "Who painted the Mona Lisa?": ["Vincent Van Gogh", "Picasso", "Leonardo Da Vinci", "Leonardo DiCaprio", "Leonardo Da Vinci"],
    "What is the largest country in the world by land mass?": ["USA", "China", "Russia", "Canada", "Russia"],
    "What is the capital of Mongolia?": ["Ulaanbaatar", "Beijing", "Seoul", "Tokyo", "Ulaanbaatar"],
    "What is the chemical symbol for potassium?": ["K", "P", "Na", "Ca", "K"],
    "What is the largest volcano in the world?": ["Mauna Loa", "Kilimanjaro", "Mount Fuji", "Mount St. Helens", "Mauna Loa"],
    "What is the capital of Iceland?": ["Reykjavik", "Oslo", "Copenhagen", "Helsinki", "Reykjavik"],
    "What is the largest island in the world?": ["Greenland", "Australia", "New Guinea", "Borneo", "Greenland"],
    "When were women first allowed to vote in New Zealand?": ["1893", "1902", "1910", "1920", "1893"],
    "What is the capital of Canada?": ["Toronto", "Ottawa", "Vancouver", "Montreal", "Ottawa"],
    "When was the first email sent?": ["1971", "1980", "1990", "2000", "1971"],
    "Who was the first person to reach the South Pole?": ["Roald Amundsen", "Robert Falcon Scott", "Ernest Shackleton", "Ferdinand Magellan", "Roald Amundsen"],
    "When was the first photograph taken?": ["1826", "1839", "1840", "1850", "1826"],
    "What planet is known as the Red Planet?": ["Venus", "Mars", "Jupiter", "Saturn", "Mars"],
    "Which gas do plants absorb from the atmosphere?": ["Oxygen", "Nitrogen", "Carbon Dioxide", "Helium", "Carbon Dioxide"],
    "What is the longest river in the world?": ["Amazon", "Nile", "Yangtze", "Mississippi", "Nile"],
    "Who developed the theory of relativity?": ["Newton", "Einstein", "Galileo", "Hawking", "Einstein"],
    "What is the main ingredient in traditional Japanese miso soup?": ["Tofu", "Seaweed", "Miso paste", "Rice", "Miso paste"],
    "Which country is famous for inventing pizza?": ["France", "Spain", "Italy", "Greece", "Italy"],
    "Which planet has the most moons?": ["Jupiter", "Saturn", "Uranus", "Neptune", "Saturn"],
    "What is the boiling point of water at sea level in Celsius?": ["90°C", "95°C", "100°C", "105°C", "100°C"],
    "Which element has the atomic number 1?": ["Helium", "Oxygen", "Hydrogen", "Carbon", "Hydrogen"],
    "What is the tallest building in the world as of 2025?": ["Shanghai Tower", "Abraj Al-Bait", "Burj Khalifa", "One World Trade Center", "Burj Khalifa"],
    "What is the currency of Brazil?": ["Peso", "Real", "Dollar", "Lira", "Real"],
    "Who wrote 'Romeo and Juliet'?": ["Charles Dickens", "William Shakespeare", "Jane Austen", "George Orwell", "William Shakespeare"],
    "What is the largest desert in the world?": ["Gobi", "Sahara", "Arctic", "Antarctic", "Antarctic"],
    "Which country has the most time zones?": ["Russia", "USA", "France", "China", "France"],
    "What part of the cell contains DNA?": ["Cytoplasm", "Nucleus", "Mitochondria", "Ribosome", "Nucleus"],
    "Which is the only continent without reptiles or snakes?": ["Asia", "Europe", "Antarctica", "North America", "Antarctica"],
    "What is the square root of 144?": ["10", "11", "12", "13", "12"],
    "Which company created the iPhone?": ["Samsung", "Google", "Microsoft", "Apple", "Apple"],
    "What is the smallest bone in the human body?": ["Stapes", "Femur", "Ulna", "Tibia", "Stapes"],
    "Who has the most over all points in the NBA?": ["Michael Jordan", "Joseph Hurndell", "LeBron James", "Kobe Bryant", "Joseph Hurndell"],
    "What is the average penis size (in mm)" : ["1", "2", "5", "6", "2"]
}
